name: Windows Build

on:
  workflow_call:
    inputs:
      ring-version:
        required: true
        type: string

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        include:
        - arch: Win32
          arch_name: i386
        - arch: x64
          arch_name: amd64
        - arch: ARM64
          arch_name: arm64

    steps:
    - name: Checkout ring-ftp
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Checkout Ring Language
      uses: actions/checkout@v4
      with:
        repository: ring-lang/ring
        path: ring
        ref: ${{ inputs.ring-version }}

    - name: Configure and Build Ring Language for ${{ matrix.arch_name }}
      shell: cmd
      run: |
        cd ring\language
        REM Use the matrix variable to set the architecture
        cmake . -A ${{ matrix.arch }}
        cmake --build . --config Release --parallel
        cmake --install .

    - name: Set RING environment variable
      run: echo "RING=$(pwd)\ring" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

    - name: Checkout curl
      uses: actions/checkout@v4
      with:
        repository: curl/curl
        path: curl
        ref: curl-8_16_0

    - name: Build curl from source
      shell: cmd
      run: |
        cd curl
        mkdir build
        cd build
        cmake -A ${{ matrix.arch }} -DCURL_USE_SCHANNEL=ON -DCURL_USE_OPENSSL=OFF -DCURL_USE_GNUTLS=OFF -DCURL_WINDOWS_SSPI=ON -DBUILD_SHARED_LIBS=OFF -DBUILD_CURL_EXE=OFF -DBUILD_TESTING=OFF -DCURL_DISABLE_INSTALL=OFF -DCURL_USE_LIBPSL=OFF -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=C:/curl ..
        cmake --build . --config Release --parallel
        cmake --install .

    - name: Configure and Build ring-ftp lib for ${{ matrix.arch_name }}
      shell: cmd
      run: |
        rmdir /s /q lib
        cmake . -A ${{ matrix.arch }} -DCMAKE_PREFIX_PATH=C:/curl
        cmake --build . --config Release --parallel

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ring-ftp-windows-${{ matrix.arch_name }}
        path: lib
